services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vdrive-app
    env_file:
      - ./.dev.env
    restart: unless-stopped
    ports:
      - "8001:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    volumes:
      - .:/var/www/html
    networks:
      - vdrive-network
  node:
    image: node:20-alpine
    container_name: vdrive-node
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: npm run dev
    ports:
      - "5173:5173"
    networks:
      - vdrive-network
  db:
    image: postgres:14
    container_name: vdrive-db
    restart: unless-stopped
    env_file:
      - ./.dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vdrive-network
    ports:
      - 5432:5432
  mailpit:
    image: axllent/mailpit
    container_name: vdrive-mailpit
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - vdrive-network
networks:
  vdrive-network:
    driver: bridge

volumes:
  postgres_data:
